version: '3.9'

services:
  plan-your-activity:
    container_name: plan-your-activity-postgres
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5433:5432"
    volumes:
      - plan-your-activity-volume:/var/lib/postgresql/data

volumes:
  plan-your-activity-volume: